# Generated by Django 3.1.7 on 2021-02-21 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20210217_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
        migrations.AddField(
            model_name='dragon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toy',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='toy',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('dragon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dragon')),
            ],
        ),
    ]
